"""empty message

Revision ID: 51ee4155ef05
Revises: 6bbbb58bbbeb
Create Date: 2024-02-09 14:33:47.708068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ee4155ef05'
down_revision = '6bbbb58bbbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
