"""empty message

Revision ID: 538f3665a1a8
Revises: 58b5c3fb595f
Create Date: 2024-03-06 00:54:30.158823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538f3665a1a8'
down_revision = '58b5c3fb595f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
