"""empty message

Revision ID: a31b7dcf097d
Revises: 214a5a0811ec
Create Date: 2024-03-03 20:44:38.523867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31b7dcf097d'
down_revision = '214a5a0811ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Avatars', schema=None) as batch_op:
        batch_op.drop_column('skin')

    # ### end Alembic commands ###
